SUBSTITUENTS = {
    "hydrogen": "[R][H]",
    # Alkanes
    "methyl": "[R]C",
    "ethyl": "[R]CC",
    "isopropyl": "[R]C(C)(C)",
    "tert-butyl": "[R]C(C)(C)(C)",
    # Alkene
    "vinyl": "[R]C=C",
    "allyl": "[R]CC=C",
    # Aryl
    "phenyl": "[R]c1ccccc1",
    "pyridyl": "[R]c1ccncc1",
    "benzyl": "[R]Cc1ccccc1",
    # Aldehydes
    "aldehyde": "[R]C=O",
    "thioaldehyde": "[R]C=S",
    # Amines
    "amino": "[R]N",
    "methylamine": "[R]NC",
    "dimethylamine": "[R]N(C)(C)",
    # Nitro
    "nitro": "[R]N(=O)(=O)",
    # Alcohol
    "hydroxyl": "[R]O",
    "thiolhydroxyl": "[R]S",
    # Azide
    "azide": "[R]-N=[N+]=[N-]",
    # Nitro
    "nitrile": "[R]-C#N",
    "isonitrile": "[R]-[N+]#[C-]",
    # Halogen
    "fluoro": "[R]-F",
    "chloro": "[R]-Cl",
    "bromo": "[R]-Br",
    # "iodo": "[R]-I",
    # Acids
    "acid": "[R]C(=O)(O)",
    "thioacid": "[R]C(=S)(O)",
    # Alkyne
    "propyne": "[R]C#C",
}
